### ISSUE TITLE
enhancement suggestion

### ISSUE THREAD

**Issue by jack99999** [TLINDEN/viking-mode#4] opened 2016-05-28 05:02 UTC
hi

i have removed viking-kill-buffer from the viking-kill-funcs list, so my maximum delete is a paragraph. when i have deleted a paragraph it is nice sometimes to delete another paragraph... but viking does nothing when i press the key again, cos it has run to the end of its list.

i don't suppose it is trivial to have an option to make viking repeat the final entry in the list? 

also, trivially, i think viking-kill-funcs would look better as viking-kill-functions. i would have spotted it quicker in the customise list...

thanks

jack

**Comment by TLINDEN** [comment] 2016-05-28 08:43
Good point(s), I'll take a look into it.
- Tom

**Comment by TLINDEN** [comment] 2016-05-28 11:02
Well then. Take a look into commit  7675a3c. There's a new function `viking-repeat-last-kill` which is by default bound to `C-S-d` (a better binding would be `M-d` but you can change this). This tries to solve this in a more generic way. You just hit `C-d` repeatedly and if you reach the kill function which you want to repeat, you just continue with `C-S-d`.

Also I rernamed the kill function list as suggested.

**Comment by TLINDEN** [comment] 2016-05-28 11:16
And commit  a1d84ed implements your suggestion: if the last kill command is not kill-buffer, just repeat this one.

**Comment by jack99999** [comment] 2016-05-28 12:56
hi tom

the new function name is fine.

your approach to make repeat more generic is a good idea.

...but i'm having some problems...

if i put the cursor on the first character in a paragraph and run viking-kill-thing-at-point, viking deletes the word and the previous blank line and says 'spaces cleared'. 

if i start inside a para and then do two viking-kill-thing-at-point so that the last one was 'line at point deleted' and then i run viking-repeat-last-kill, every time i run viking-repeat-last-kill it says 'word right of point deleted' and then 'spaces cleared'.

the 'spaces cleared' messages overwrite the previous messages, so unless you pay attention it looks as though viking always says just 'spaces cleared. maybe it's better not to have a 'spaces cleared' message at all?

am i doing something wrong...is this weird behaviour because i am running  viking-kill-thing-at-point? 

thanks
jack

**Comment by TLINDEN** [comment] 2016-05-28 17:43
There was a bug, viking-repeat-last-kill didn't work at all, it just repeated viking-kill-word, which clears spaces after each run and this was too verbose.

Anyway, it's fixed now.

**Comment by jack99999** [comment] 2016-05-28 18:44
hi tom

viking-repeat-last-kill is now working properly, as you say.

i'm having trouble with viking-kill-thing-at-point. if i put the cursor on the first character of a para and call viking-kill-thing-at-point, the word is deleted and the previous blank line, even though i have disabled viking-greedy-kill. maybe i'm misunderstanding something here?

if i then call viking-kill-thing-at-point another 2 times, viking deletes the line at point but also inserts a space at the beginning of the paragraph. this is just strange.

cheers

jack

**Comment by TLINDEN** [comment] 2016-05-28 19:06
Hm, I can't reproduce this. Could you re-try with a bare-bones config like:

```
(add-to-list 'load-path (expand-file-name "~/.emacs.d/lisp"))
(require 'viking-mode)
(viking-global-mode)
(setq viking-greedy-kill nil)
```

and start emacs with this config like:

```
emacs -l testconfig -q
```

Does the behavior then persist?

**Comment by jack99999** [comment] 2016-05-28 19:12
arrgghhh. i realised the moment i saw you mesage. it's my stupidity. i modified viking-greedy-kill in the customise UI and it just cleared the value instead of setting it to nil.

yes, it's all working. my apologies for wasting your time.

jack

**Comment by TLINDEN** [comment] 2016-05-28 19:44
You're welcome, that's no wasted time :)

Tom

**Closed as completed by TLINDEN** 2016-05-28 19:44 UTC
Labels: enhancement
